### ISSUE TITLE
Improve `update_content.sh`

### ISSUE THREAD

**Issue by athakral** [alrra/dotfiles#20]
If the user chooses not to install the applications/utilities and then tries to update the files, on Ubuntu for example, `xclip` would not be there, causing the script to be stuck in an infinite loop.

**Comment by alrra** [comment]
@athakral Thanks for opening this issue!

> If the user chooses not to install the applications/utilities and then tries to update the files, on Ubuntu for example, `xclip` would not be there, causing the script to be stuck in an infinite loop.

That happens because, in that case, the user needs to manually copy and [add the public SSH key to their GitHub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).

--

I've improved the `update_content.sh` script so that it provides more information in all possible cases.
