### ISSUE TITLE
Mac App Store CLI

### ISSUE THREAD

**Issue by rugaard** [alrra/dotfiles#35]
It would be incredible cool, if you could implement the Mac App Store CLI (like you did with Homebrew and your `brew_install` cmd):

https://github.com/mas-cli/mas

Into your dotfiles. This is basically the only thing I personally need for your dotfiles to be absolutely perfect! 😎

HUGE thumbs up for the best dotfiles repo on Github 👍

**Comment by alrra** [comment]
> It would be incredible cool, if you could implement the Mac App Store CLI 

@rugaard I personally don't have a need for such a thing since I rarely install anything from the `App Store` besides `Xcode`.

To give you an example, here is the current list of installed applications:

```bash
$ mas list
497799835 Xcode (8.0)
```

> This is basically the only thing I personally need

That is a good reason to start your own `dotfiles` repository. Better yet, if you consider this project to be a good starting point, fork it, try to understand what the code does, and customize it to better suit your needs.

> HUGE thumbs up for the best dotfiles repo on Github 👍

Thanks! 😊

**Comment by rugaard** [comment]
Fair point @alrra 👍 

I might just give a try with a personalized version of your files. They are really, really good 😎

**Comment by michelegera** [comment]
Hi @rugaard, I second @alrra’s comment. I’ve forked and customized this repo and it’s been incredibly useful for me.

Should you need a starting point/inspiration, [this is how I install MAS apps](https://github.com/michelegera/dotfiles/commit/a59b9e59e38e9d53866f88b15b188544cc50b40c).

**Comment by rugaard** [comment]
@michelegera Thanks a lot, man. I'm kind of a rookie when it comes to shell scripting, but I think it's quite fun. So the more inspiration I can get, the better. So thanks a lot, man!
