### ISSUE TITLE
Ask before installing so many browsers?

### ISSUE THREAD

**Issue by Naman-ntc** [alrra/dotfiles#64]
The install script install too many browsers (atleast in ubuntu), I think it should ask user whether download or not a particular browser.
What do you think?
I can make a PR if you agree

**Comment by Naman-ntc** [comment]
Well yeah kinda true

**Comment by FredLackeyOfficial** [comment]
@Naman-ntc ... the way [I handle this](https://github.com/FredLackey/dotfiles) is with a few tweaks to @alrra 's function where he detects the OS.  I return a more formal OS name including the version and environment.  For example, instead of returning just "ubuntu" I return "ubuntu-18-vm", "ubuntu-18-pm", or "ubuntu-18-wsl".  The middle part gives me a version number so my installs can be tweaked.  And, finally, the suffix indicates if it is a virtual machine, physical machine, or running in the Windows Subsystem for Linux.  The end result allows me to benefit from 99.9999% of @alrra 's code but gives me the ability to tweak what I need for each environment.

Oh, and I also added a few questions to ask about drivers... System76 or NVIDIA... to account for the various machines I use.

And, finally, every six months or so, I use [Beyond Compare](https://scootersoftware.com/index.php) to see what enhancements I'm missing.

**Comment by FredLackeyOfficial** [comment]
@Naman-ntc ... the way [I handle this](https://github.com/FredLackey/dotfiles) is with a few tweaks to @alrra 's function where he detects the OS.  I return a more formal OS name including the version and environment.  For example, instead of returning just "ubuntu" I return "ubuntu-18-vm", "ubuntu-18-pm", or "ubuntu-18-wsl".   The first part gives me the OS name and returns "macos", "ubuntu" or "mint."  The middle part gives me a version number so my installs can be tweaked.  And, finally, the suffix indicates if it is a virtual machine, physical machine, or running in the Windows Subsystem for Linux.  The end result allows me to benefit from 99.9999% of @alrra 's code but gives me the ability to tweak what I need for each environment.

Oh, and I also added a few questions to ask about drivers... System76 or NVIDIA... to account for the various machines I use.

And, finally, every six months or so, I use [Beyond Compare](https://scootersoftware.com/index.php) to see what enhancements I'm missing.
