### ISSUE TITLE
bash_completion not found 

### ISSUE THREAD

**Issue by JsBlueCat** [alrra/dotfiles#86]
thanks for a lot for your magical code. 
i run the code but when i use shell to loginin it, it throw out ```/bash_completion``` not found
then i look thought in your code in the src/shell/bash_completion i found that ```$OS/bash_completion``` but when it run the $OS there is nothing to show. i don't know how to solve it.  can you tell me?  

```
dotfiles@cery-ll-home:~$ bash
Segmentation fault (core dumped)
```
and the bash return core dumped..

**Comment by alrra** [comment]
@JsBlueCat Can you provide more details? What OS are you using? How are you running things? etc.

---

> i found that $OS/bash_completion but when it run the $OS there is nothing to show.

The `$OS` is determined and set here:

https://github.com/alrra/dotfiles/blob/edcc6cd9713685a94a901c5f46b8a92bbe458393/src/shell/bash_profile#L29

right before the shell files are sourced:

https://github.com/alrra/dotfiles/blob/edcc6cd9713685a94a901c5f46b8a92bbe458393/src/shell/bash_profile#L33-L40

**Comment by JsBlueCat** [comment]
> @JsBlueCat Can you provide more details? What OS are you using? How are you running things? etc.
> 
> > i found that $OS/bash_completion but when it run the $OS there is nothing to show.
> 
> The `$OS` is determined and set here:
> 
> https://github.com/alrra/dotfiles/blob/edcc6cd9713685a94a901c5f46b8a92bbe458393/src/shell/bash_profile#L29
> 
> right before the shell files are sourced:
> 
> https://github.com/alrra/dotfiles/blob/edcc6cd9713685a94a901c5f46b8a92bbe458393/src/shell/bash_profile#L33-L

> @JsBlueCat Can you provide more details? What OS are you using? How are you running things? etc.
> 
> > i found that $OS/bash_completion but when it run the $OS there is nothing to show.
> 
> The `$OS` is determined and set here:
> 
> https://github.com/alrra/dotfiles/blob/edcc6cd9713685a94a901c5f46b8a92bbe458393/src/shell/bash_profile#L29
> 
> right before the shell files are sourced:
> 
> https://github.com/alrra/dotfiles/blob/edcc6cd9713685a94a901c5f46b8a92bbe458393/src/shell/bash_profile#L33-L40

i use ubuntu 20.04lts
very strangely, when logging with shell it will throw that error

**Comment by alrra** [comment]
It seem the issue happens because on Ubuntu `/usr/share/bash-completion/bash_completion` sources `~/.bash_completion`, which will source `/usr/share/bash-completion/bash_completion` and so on, thus, creating an infinite loop.

![Image showing the lines in /usr/share/bash-completion/bash_completion where ~/.bash_completion is sourced](https://user-images.githubusercontent.com/1223565/111430269-5c438c80-86b7-11eb-80c9-de00d3d7a352.png)


---

@JsBlueCat I pushed a fix. After you fetch the latest changes you can fix your environment by running (from the root of the dotfiles directory):

```sh
rm -rf ~/.bash_completion && ./src/os/create_symbolic_links.sh
```

---

@JsBlueCat Thanks for opening this issue!
